sudo: required
language: node_js
cache: yarn
node_js:
  - "14.17.0"
services:
  - docker
before_install:
  - docker pull trufflesuite/ganache-cli
  - docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest -h 0.0.0.0
install:
  - yarn global add coveralls
  - yarn install
script:
  - yarn coverage && cat coverage/lcov.info | coveralls
